# Generated by Django 5.0.3 on 2024-03-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='default_file.txt', null=True, upload_to='media/'),
        ),
    ]
