# Generated by Django 5.0.3 on 2024-04-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='default_img.txt', null=True, upload_to='media/'),
        ),
    ]
