# Generated by Django 5.0.3 on 2024-04-05 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='indicator_or_strategy',
            field=models.CharField(choices=[('Indicator', 'Indicator'), ('Strategy', 'Strategy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_or_product',
            field=models.CharField(choices=[('Item', 'Item'), ('Product', 'Product')], max_length=100, null=True),
        ),
    ]
