# Generated by Django 5.0.3 on 2024-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indicator_or_strategy',
            field=models.CharField(choices=[('Package', 'Indicator'), ('Package', 'Strategy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_or_product',
            field=models.CharField(choices=[('Item', 'Indicator'), ('Item', 'Strategy')], max_length=100, null=True),
        ),
    ]
