# Generated by Django 5.0.3 on 2024-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='/static/Images/product.png', null=True, upload_to='static/Images'),
        ),
    ]
