# Generated by Django 5.0.3 on 2024-04-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_product_indicator_or_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_or_product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='indicator_or_strategy',
            new_name='Package',
        ),
    ]
