# Generated by Django 5.0.3 on 2024-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_rename_item_or_product_product_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Package',
        ),
        migrations.AddField(
            model_name='product',
            name='indicator_or_strategy',
            field=models.CharField(choices=[('Indicator', 'Indicator'), ('Strategy', 'Strategy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_or_package',
            field=models.CharField(choices=[('Item', 'Item'), ('Package', 'Package')], max_length=100, null=True),
        ),
    ]
