# Generated by Django 5.0.3 on 2024-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_remove_product_item_remove_product_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indicator_or_strategy',
            field=models.CharField(choices=[('Indicator', 'indicator'), ('Strategy', 'strategy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_or_package',
            field=models.CharField(choices=[('Item', 'item'), ('Package', 'package')], max_length=100, null=True),
        ),
    ]
