# Generated by Django 5.0.3 on 2024-04-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_alter_product_indicator_or_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indicator_or_strategy',
            field=models.CharField(choices=[('indicator', 'indicator'), ('strategy', 'strategy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_or_package',
            field=models.CharField(choices=[('item', 'item'), ('package', 'package')], max_length=100, null=True),
        ),
    ]
