# Generated by Django 5.0.3 on 2024-04-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_product_image'),
        ('home_app', '0013_alter_product_indicator_or_strategy_and_more'),
    ]

    operations = [
    ]
