# Generated by Django 5.0.3 on 2024-04-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=300),
        ),
    ]
